<a href="https://colab.research.google.com/github/bhuvaneswarignanasekar/Data-analysis/blob/main/decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sklearn
from sklearn import tree

In [2]:
data=pd.read_excel('/content/AlienMushrooms.xlsx')
data.head()

   White  Tall  Frilly Edible
0      0     0       0      F
1      0     0       0      F
2      0     0       0      F
3      0     0       0      T
4      0     0       1      T

In [3]:
X=data.copy()
y=X['Edible']
X.drop(['Edible'],axis=1,inplace=True)

In [4]:
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(X, y)

In [5]:
import pydotplus 
import collections 
 
# for a two-class tree, call this function like this: 
# writegraphtofile(clf, ('F', 'T'), dirname+graphfilename) 
def writegraphtofile(classifier, classnames, pathname): 
    dot_data = tree.export_graphviz(clf, out_file=None,    # merely to write the tree out 
                         class_names=classnames, 
                         feature_names=['White','Tall','Frilly'], 
                         filled=True, rounded=True, 
                         special_characters=True) 
    graph = pydotplus.graph_from_dot_data(dot_data) 
    colors = ('lightblue', 'green') 
    edges = collections.defaultdict(list) 
    for edge in graph.get_edge_list(): 
        edges[edge.get_source()].append(int(edge.get_destination())) 
    for edge in edges: 
        edges[edge].sort() 
        for i in range(2): 
            dest = graph.get_node(str(edges[edge][i]))[0] 
            dest.set_fillcolor(colors[i]) 
    graph.write_png(pathname)

In [6]:
writegraphtofile(clf, ('F','T'), '/content/AlienMushrooms.png')

In [31]:
flare=pd.read_excel('/content/FlareData.xlsx')

In [32]:
flare.head()

  Zurich Class Spot Size Spot Dist  ...  C class  M class  X class
0            C         S         O  ...        0        0        0
1            D         S         O  ...        0        0        0
2            C         S         O  ...        0        0        0
3            D         S         O  ...        0        0        0
4            D         A         O  ...        0        0        0

[5 rows x 13 columns]

In [33]:
flare.drop(['M class','X class'],axis=1, inplace=True)

In [34]:
flare['Zurich Class']=pd.factorize(flare['Zurich Class'])[0]

In [35]:
flare['Spot Size']=pd.factorize(flare['Spot Size'])[0]
flare['Spot Dist']=pd.factorize(flare['Spot Dist'])[0]

In [36]:
flare.head()

   Zurich Class  Spot Size  Spot Dist  ...  Area  Spot Area  C class
0             0          0          0  ...     1          2        0
1             1          0          0  ...     1          2        0
2             0          0          0  ...     1          1        0
3             1          0          0  ...     1          2        0
4             1          1          0  ...     1          2        0

[5 rows x 11 columns]

In [37]:
flare.columns

Index(['Zurich Class', 'Spot Size', 'Spot Dist', 'Activity', 'Evolution',
       'Prev Activity', 'Historical', 'New Historical', 'Area', 'Spot Area',
       'C class'],
      dtype='object')

In [38]:
flare_x=flare.copy()
flare_y=flare_x['C class']
flare_x.drop(['C class'],axis=1,inplace=True)
clg = tree.DecisionTreeClassifier(criterion='entropy',max_depth=4)
clg = clg.fit(flare_x, flare_y)

In [39]:
def writegraphtofile(classifier, classnames, pathname): 
    dot_data = tree.export_graphviz(clg, out_file=None,    # merely to write the tree out 
                         class_names=classnames, 
                         feature_names=['Zurich Class', 'Spot Size', 'Spot Dist', 'Activity', 'Evolution',
       'Prev Activity', 'Historical', 'New Historical', 'Area', 'Spot Area'],
                         filled=True, rounded=True, 
                         special_characters=True) 
    graph = pydotplus.graph_from_dot_data(dot_data) 
    colors = ('lightblue', 'green') 
    edges = collections.defaultdict(list) 
    for edge in graph.get_edge_list(): 
        edges[edge.get_source()].append(int(edge.get_destination())) 
    for edge in edges: 
        edges[edge].sort() 
        for i in range(2): 
            dest = graph.get_node(str(edges[edge][i]))[0] 
            dest.set_fillcolor(colors[i]) 
    graph.write_png(pathname)

In [40]:
writegraphtofile(clg, ('0','1','2'), '/content/flare_entropy.png')

In [41]:
clfgini = tree.DecisionTreeClassifier(criterion='gini',max_depth=4)
clfgini = clfgini.fit(flare_x, flare_y)

In [42]:
writegraphtofile(clg, ('0','1','2'), '/content/flare_gini.png')